### ISSUE TITLE
Ссылки на странице [Contacts]

### ISSUE THREAD

**Issue by Blackk88** [Softocean/softocean_landing#91]
**Describe the bug**
На странице контактов ссылки открываются в той же вкладке.

**To Reproduce**
1. Перейти на страницу "Contacts"
2. Нажать на любую ссылку "Social Network"
3. Ссылка открывается в том же окне

**Expected behavior**
При переходе по ссылке она должна открываться в новой вкладке. 

**Screenshots**
![Screenshot 2023-11-04 at 10 04 41 AM](https://github.com/Softocean/landing/assets/108989350/f3595908-547a-42c8-8091-8760a366e3c4)

**Comment by 63phc** [comment]
@Blackk88 нужно добавить 
GitHub - https://github.com/Softocean
Инста)) - https://www.instagram.com/softoceangmbh
